void monitoreo() {
  /*Serial.print("distancia1:");
    Serial.print(distancia1);
    Serial.print("  distancia2:");
    Serial.print(distancia2);
    Serial.print("  distancia3:");
    Serial.println(distancia3);
    /*Serial.print("Fdistancia1:");
    Serial.print(filtroDistancia1);
    Serial.print("  Fdistancia2:");
    Serial.print(filtroDistancia2);
    Serial.print("  Fdistancia3:");
    Serial.println(filtroDistancia3);
    Serial.print("Porcentaje1:");
    Serial.print(porcentaje1);
    Serial.print("  Porcentaje2:");
    Serial.print(porcentaje2);
    Serial.print("  Porcentaje3:");
    Serial.println(porcentaje3);
    Serial.print("FPorcentaje1:");
    Serial.print(Fporcentaje1);
    Serial.print("  FPorcentaje2:");
    Serial.print(Fporcentaje2);
    Serial.print("  FPorcentaje3:");
    Serial.println(Fporcentaje3);
    /*Serial.print("Porcentaje1C:");
    Serial.print(constrainedPorcentaje1);
    Serial.print("  Porcentaje2C:");
    Serial.print(constrainedPorcentaje2);
    Serial.print("  Porcentaje3C:");
    Serial.println(constrainedPorcentaje3);
    Serial.print("Porcentaje1R:");
    Serial.print(porcentajeReal1);
    Serial.print("  Porcentaje2R:");
    Serial.print(porcentajeReal2);
    Serial.print("  Porcentaje3R:");
    Serial.println(porcentajeReal3);*/

  //  Serial.println(constrainedPorcentaje3);
  //  Serial.println(valor);
  //  Serial.print("TiempoHor:");
  //  Serial.print( TiempoHor);
  //  Serial.print("  TiempoMin:");
  //  Serial.println( TiempoMin);
  //  Serial.print("TiempoHorUso:");
  //  Serial.print( TiempoHorUso);
  //  Serial.print("  TiempoMinUso:");
  //  Serial.println( TiempoMinUso);
  //  Serial.print("TInicioMezclado:");
  //  Serial.println( TInicioMezclado);
  //  //  Serial.print("Cantidad1:");
  //  //  Serial.print( cantidad1);
  //  //  Serial.print("  Cantidad2:");
  //  //  Serial.println( cantidad2);
  //  //  Serial.print("activarMezcla:");
  //  //  Serial.print( activarMezcla);
  //    Serial.print("  terminoLlenadoLiquido1:");
  //    Serial.print( terminoLlenadoLiquido1);
  //    Serial.print("  terminoLlenadoLiquido2:");
  //    Serial.println( terminoLlenadoLiquido2);
  //  Serial.print(" arranque2:");
  //  Serial.println(arranque2);
  //

  Serial.println(Ingrediente1);
  Serial.println(Ingrediente2);
  Serial.print("TInicioMezclado:");
  Serial.print(TInicioMezclado);
  Serial.print("  TiempoRestante:");
  Serial.println(TiempoRestante);
}
