# Generated by Django 4.2.2 on 2024-12-13 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_horas', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('TECNICA', 'Técnica'), ('SEGURIDAD', 'Seguridad'), ('HIGIENE', 'Higiene'), ('SALUD', 'Salud'), ('RRHH', 'Recursos Humanos')], default='TECNICA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CronogramaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoComprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('litros', 'Litros'), ('unidades', 'Unidades')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('rango', models.CharField(choices=[('1', 'Director'), ('2', 'Gerente'), ('3', 'Jefe de Sección'), ('4', 'Coordinador'), ('5', 'Especialista'), ('6', 'Empleado'), ('7', 'Pasante'), ('8', 'Contratista')], max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('contacto', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('cbu', models.CharField(blank=True, max_length=22, null=True)),
                ('alias_bancario', models.CharField(blank=True, max_length=50, null=True)),
                ('clave', models.CharField(default='', editable=False, max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DESPEDIDO', 'Despedido'), ('JUBILADO', 'Jubilado'), ('OTRO', 'Otro')], default='ACTIVO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_m2', models.FloatField()),
                ('usados_m2', models.FloatField(default=0)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='polls.fabrica')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('numero_serie', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('RESIDUO', 'Residuo'), ('PRODUCTO', 'Producto'), ('MATERIA PRIMA', 'Materia Prima'), ('REPUESTO', 'Repuesto'), ('COMPONENTE', 'Componente'), ('MÁQUINA', 'Máquina'), ('ACTUADOR/SENSOR', 'Actuador/Sensor'), ('HERRAMIENTA', 'Herramienta'), ('VEHÍCULO', 'Vehículo'), ('ELECTRODOMÉSTICO', 'Electrodoméstico'), ('VARIOS', 'Varios')], max_length=40)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(default='unidades', max_length=50)),
                ('espacio_m2', models.FloatField()),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='polls.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ART', 'ART'), ('Seguro', 'Seguro'), ('Equipamiento', 'Equipamiento'), ('Materia Prima', 'Materia Prima'), ('Transporte', 'Transporte'), ('Publicidad', 'Publicidad'), ('Ayuda Legal', 'Ayuda Legal'), ('Ayuda Financiera', 'Ayuda Financiera'), ('Otro', 'Otro')], max_length=50)),
                ('contacto', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion_mantenimiento', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=50)),
                ('devuelto_a_origen', models.BooleanField(default=False)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='polls.iteminventario')),
                ('empleado_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tarifa_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('clave', models.CharField(editable=False, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True)),
                ('autorizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_autorizadas', to='polls.empleado')),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nueva_direccion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('autorizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_autorizadas', to='polls.empleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_trabajadores', models.PositiveIntegerField()),
                ('tamano_seccion', models.FloatField()),
                ('agenda', models.TextField(blank=True, null=True)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='polls.fabrica')),
            ],
            options={
                'unique_together': {('nombre', 'fabrica')},
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('solicitada_por', models.CharField(max_length=100)),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True)),
                ('autorizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_autorizadas', to='polls.empleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPagoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque')], default='TRANSFERENCIA', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_por_tarea', to='polls.empleado')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados', to='polls.registromantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='seccion_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_recibidos', to='polls.seccion'),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='seccion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_realizados', to='polls.seccion'),
        ),
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=20)),
                ('categoria', models.CharField(choices=[('SALARIOS', 'Salarios'), ('IMPUESTOS', 'Impuestos'), ('PROVEEDORES', 'Proveedores'), ('SERVICIOS', 'Servicios Públicos (agua, luz, etc.)'), ('VENTAS', 'Ventas'), ('OTROS', 'Otros')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('factura', models.FileField(blank=True, help_text='Carga una factura o recibo en PDF relacionado con la transacción.', null=True, upload_to='finanzas/facturas/%Y/%m/%d/')),
                ('imagen_factura', models.ImageField(blank=True, help_text='Carga una imagen del recibo relacionado con la transacción.', null=True, upload_to='finanzas/imagenes/%Y/%m/%d/')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_financieros', to='polls.fabrica')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFichaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichajes', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Líquido', 'Líquido'), ('Sólido', 'Sólido'), ('Combinado', 'Combinado')], max_length=50)),
                ('ingredientes', models.ManyToManyField(related_name='recetas', through='polls.DetalleReceta', to='polls.iteminventario')),
            ],
        ),
        migrations.CreateModel(
            name='PruebasMedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prueba', models.DateField(default=django.utils.timezone.now)),
                ('tipo_prueba', models.CharField(max_length=100)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, help_text='Sube un archivo relacionado con la prueba médica (PDF, Word, etc.)', null=True, upload_to='pruebas_medicas/documentos/%Y/%m/%d/')),
                ('imagen', models.ImageField(blank=True, help_text='Sube una imagen relacionada con la prueba médica (JPG, PNG, etc.)', null=True, upload_to='pruebas_medicas/imagenes/%Y/%m/%d/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_medicas', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('nuevo_rango', models.CharField(choices=[('1', 'Director'), ('2', 'Gerente'), ('3', 'Jefe de Sección'), ('4', 'Coordinador'), ('5', 'Especialista'), ('6', 'Empleado'), ('7', 'Pasante'), ('8', 'Contratista')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('solicitada_por', models.CharField(max_length=100)),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True)),
                ('autorizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_autorizadas', to='polls.empleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('cantidad_producida', models.FloatField()),
                ('tipo_producto', models.CharField(choices=[('Líquido', 'Líquido'), ('Sólido', 'Sólido'), ('Combinado', 'Combinado')], max_length=50)),
                ('cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones', to='polls.cronogramaseccion')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='polls.receta')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='polls.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
                ('total_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.FileField(blank=True, help_text='Carga una factura o recibo relacionado con el pedido.', null=True, upload_to='pedidos_proveedor/facturas/%Y/%m/%d/')),
                ('imagen_factura', models.ImageField(blank=True, help_text='Carga una imagen del recibo relacionado con el pedido.', null=True, upload_to='pedidos_proveedor/imagenes/%Y/%m/%d/')),
                ('empleado_encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_proveedor_realizados', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='items_pedidos_proveedor', through='polls.DetallePedidoProveedor', to='polls.iteminventario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='polls.proveedor')),
                ('vehiculo_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_usados_en_pedidos', to='polls.iteminventario')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoComprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('total_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.FileField(blank=True, help_text='Carga una factura o recibo relacionado con el pedido.', null=True, upload_to='pedidos_comprador/facturas/%Y/%m/%d/')),
                ('imagen_factura', models.ImageField(blank=True, help_text='Carga una imagen del recibo relacionado con el pedido.', null=True, upload_to='pedidos_comprador/imagenes/%Y/%m/%d/')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='polls.comprador')),
                ('empleado_encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_realizados', to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(related_name='pedidos', through='polls.DetallePedidoComprador', to='polls.iteminventario')),
                ('vehiculo_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_transportados', to='polls.iteminventario')),
            ],
        ),
        migrations.CreateModel(
            name='PagoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('total_horas_normales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_mensuales', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('tipo', models.CharField(choices=[('maternidad', 'Maternidad'), ('psiquiatrica', 'Psiquiatrica'), ('enfermedad', 'Enfermedad'), ('por accidente', 'Por accidente'), ('problemas familiares', 'Problemas familiares')], default='Maternidad', max_length=20)),
                ('gose_sueldo', models.CharField(choices=[('sí', 'Sí'), ('no', 'No')], default='Si', max_length=20)),
                ('autorizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_autorizadas', to='polls.empleado')),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='polls.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='polls.proveedor'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.seccion'),
        ),
        migrations.CreateModel(
            name='HistorialMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('AL_INVENTARIO', 'A Inventario'), ('A_SECCION', 'A Sección')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='polls.iteminventario')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='polls.seccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoVacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=10)),
                ('estado_nuevo', models.CharField(max_length=10)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.empleado')),
                ('vacacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='polls.vacacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EventoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_especiales', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dato', models.FloatField()),
                ('unidad', models.CharField(default='N/A', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='polls.iteminventario')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField()),
                ('estado', models.CharField(choices=[('COMPLETADO', 'Completado'), ('EN_PROCESO', 'En proceso'), ('NO_INICIADO', 'No iniciado')], default='NO_INICIADO', max_length=20)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='polls.capacitacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='polls.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='fabrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='polls.fabrica'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_directos', to='polls.seccion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.tipotarifa'),
        ),
        migrations.CreateModel(
            name='EjecucionReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=50)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='polls.receta')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='polls.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_generada', models.FloatField()),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('litros', 'Litros'), ('unidades', 'Unidades')], max_length=50)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_residuos', to='polls.produccion')),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_residuos', to='polls.iteminventario')),
            ],
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_receta', to='polls.iteminventario'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='polls.receta'),
        ),
        migrations.AddField(
            model_name='detallepedidoproveedor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido_proveedor', to='polls.iteminventario'),
        ),
        migrations.AddField(
            model_name='detallepedidoproveedor',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='polls.pedidoproveedor'),
        ),
        migrations.AddField(
            model_name='detallepedidocomprador',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='polls.pedidocomprador'),
        ),
        migrations.AddField(
            model_name='detallepedidocomprador',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='polls.iteminventario'),
        ),
        migrations.AddField(
            model_name='cronogramaseccion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='polls.iteminventario'),
        ),
        migrations.AddField(
            model_name='cronogramaseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='polls.seccion'),
        ),
        migrations.CreateModel(
            name='BomboAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_total_litros', models.FloatField()),
                ('capacidad_usada_litros', models.FloatField(default=0)),
                ('tipo_contenido', models.CharField(choices=[('LIQUIDO', 'Líquido'), ('RESIDUO', 'Residuo')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombos', to='polls.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='AccidenteLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accidente', models.DateField()),
                ('descripcion', models.TextField()),
                ('indemnizacion_autorizada', models.BooleanField(default=False)),
                ('proveedor_seguro', models.CharField(max_length=255)),
                ('monto_indemnizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_incapacidad', models.PositiveIntegerField(default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidentes', to='polls.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Desconocido', max_length=100)),
                ('antiguedad_minima', models.PositiveIntegerField(default=0)),
                ('antiguedad_maxima', models.PositiveIntegerField(default=0)),
                ('dias_vacaciones', models.PositiveIntegerField()),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_vacaciones', to='polls.fabrica')),
            ],
            options={
                'unique_together': {('pais', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='EmpleadoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='polls.empleado')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_historial', to='polls.seccion')),
            ],
            options={
                'unique_together': {('empleado', 'seccion', 'fecha_union')},
            },
        ),
    ]
