# Generated by Django 5.2.13 on 2026-04-30 23:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('broker_url', models.CharField(help_text='URL del broker MQTT', max_length=255)),
                ('puerto', models.IntegerField(default=1883)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('usar_tls', models.BooleanField(default=False)),
                ('keep_alive', models.IntegerField(default=60, help_text='Keep alive en segundos')),
                ('topic_base', models.CharField(default='scada/', help_text='Topic base para suscripciones', max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración MQTT',
                'verbose_name_plural': 'Configuraciones MQTT',
            },
        ),
        migrations.RemoveField(
            model_name='empleadocapacitacion',
            name='capacitacion',
        ),
        migrations.RemoveField(
            model_name='pedidocomprador',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='detallepedidocomprador',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedidocomprador',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedidocomprador',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedor',
            name='item',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedor',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='items',
        ),
        migrations.RemoveField(
            model_name='detalleresiduos',
            name='produccion',
        ),
        migrations.RemoveField(
            model_name='detalleresiduos',
            name='residuo',
        ),
        migrations.RemoveField(
            model_name='empleadocapacitacion',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='estadoitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='eventoespecial',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='falta',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='historialestadovacacion',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='historialestadovacacion',
            name='vacacion',
        ),
        migrations.RemoveField(
            model_name='licencia',
            name='autorizada_por',
        ),
        migrations.RemoveField(
            model_name='licencia',
            name='solicitada_por',
        ),
        migrations.RemoveField(
            model_name='pagomensual',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='pedidocomprador',
            name='empleado_encargado',
        ),
        migrations.RemoveField(
            model_name='pedidocomprador',
            name='vehiculo_usado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='empleado_encargado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='vehiculo_usado',
        ),
        migrations.AlterUniqueTogether(
            name='politicavacaciones',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='politicavacaciones',
            name='fabrica',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='autorizada_por',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='iteminventario',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pruebasmedicas',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='registrofichaje',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='registrofinanciero',
            name='fabrica',
        ),
        migrations.RemoveField(
            model_name='registropagotarea',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='registropagotarea',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='sancion',
            name='autorizada_por',
        ),
        migrations.RemoveField(
            model_name='sancion',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_tarifa',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='autorizado_por',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='vacacion',
            name='autorizada_por',
        ),
        migrations.RemoveField(
            model_name='vacacion',
            name='solicitada_por',
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol_actual',
            field=models.CharField(blank=True, help_text='Rol o cargo actual', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(choices=[('OPERARIO', 'Operario'), ('SUPERVISOR', 'Supervisor'), ('TECNICO', 'Técnico'), ('JEFE_PLANTA', 'Jefe de Planta'), ('ADMINISTRATIVO', 'Administrativo')], default='OPERARIO', help_text='Tipo de empleado', max_length=50),
        ),
        migrations.AddField(
            model_name='fabrica',
            name='alarmas_activas',
            field=models.IntegerField(default=0, help_text='Número de alarmas activas'),
        ),
        migrations.AddField(
            model_name='fabrica',
            name='consumo_energia',
            field=models.FloatField(default=0, help_text='Consumo de energía en kWh'),
        ),
        migrations.AddField(
            model_name='fabrica',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Crítico'), ('OFFLINE', 'Offline')], default='OPERATIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='fabrica',
            name='porcentaje_eficiencia',
            field=models.FloatField(default=0, help_text='Porcentaje de eficiencia (0-100)'),
        ),
        migrations.AddField(
            model_name='fabrica',
            name='porcentaje_produccion',
            field=models.FloatField(default=0, help_text='Porcentaje de producción actual (0-100)'),
        ),
        migrations.AddField(
            model_name='fabrica',
            name='temperatura_promedio',
            field=models.FloatField(default=0, help_text='Temperatura promedio en °C'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='categoria',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('MATERIA PRIMA', 'Materia Prima')], max_length=40),
        ),
        migrations.CreateModel(
            name='DispositivoSCADA',
            fields=[
                ('numero_serie', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('SENSOR_TEMPERATURA', 'Sensor de Temperatura'), ('SENSOR_PRESION', 'Sensor de Presión'), ('SENSOR_FLUJO', 'Sensor de Flujo'), ('SENSOR_NIVEL', 'Sensor de Nivel'), ('SENSOR_HUMEDAD', 'Sensor de Humedad'), ('MOTOR', 'Motor'), ('BOMBA', 'Bomba'), ('VALVULA', 'Válvula'), ('PLC', 'PLC'), ('HMI', 'HMI'), ('MEZCLADORA', 'Mezcladora'), ('ENVASADORA', 'Envasadora'), ('TRANSPORTADOR', 'Transportador'), ('ROBOT', 'Robot'), ('OTRO', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MANTENIMIENTO', 'En Mantenimiento'), ('ERROR', 'Error')], default='OFFLINE', max_length=20)),
                ('topic_mqtt', models.CharField(blank=True, help_text='Topic MQTT para este dispositivo', max_length=255, null=True)),
                ('fecha_instalacion', models.DateField(default=django.utils.timezone.now)),
                ('ultima_lectura', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='polls.inventario')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='polls.seccion')),
            ],
            options={
                'verbose_name': 'Dispositivo SCADA',
                'verbose_name_plural': 'Dispositivos SCADA',
            },
        ),
        migrations.CreateModel(
            name='ComunicacionMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, help_text='Topic MQTT (ej: scada/planta1/sensor1/temperatura)', max_length=255)),
                ('payload', models.TextField(help_text='Datos enviados/recibidos (JSON, plain text, etc.)')),
                ('direccion', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('RECIBIDO', 'Recibido')], help_text='Si fue publicado o recibido', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento exacto de la comunicación')),
                ('qos', models.IntegerField(default=0, help_text='Quality of Service MQTT (0, 1, o 2)')),
                ('exitoso', models.BooleanField(default=True, help_text='Si la comunicación fue exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si falló', null=True)),
                ('configuracion', models.ForeignKey(help_text='Configuración MQTT utilizada', on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='polls.configuracionmqtt')),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Dispositivo relacionado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones_mqtt', to='polls.dispositivoscada')),
            ],
            options={
                'verbose_name': 'Comunicación MQTT',
                'verbose_name_plural': 'Comunicaciones MQTT',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_medida', models.CharField(default='L', max_length=20)),
                ('stock_actual', models.FloatField(default=0)),
                ('stock_minimo', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('bombo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='polls.bomboalmacenamiento')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(default='N/A', max_length=20)),
                ('calidad', models.CharField(default='GOOD', help_text='GOOD, BAD, UNCERTAIN', max_length=20)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='polls.dispositivoscada')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField(default='08:00')),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField(default='17:00')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('progreso', models.IntegerField(default=0, help_text='Porcentaje de progreso 0-100')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='polls.dispositivoscada')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='polls.fabrica')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to='polls.receta')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(help_text='Nombre del producto (copiado de la orden)', max_length=200)),
                ('cantidad_planificada', models.IntegerField(help_text='Cantidad que se planificó producir')),
                ('cantidad_producida', models.IntegerField(help_text='Cantidad realmente producida')),
                ('porcentaje_cumplimiento', models.FloatField(help_text='Porcentaje de cumplimiento (producida/planificada * 100)')),
                ('tiempo_planificado', models.DurationField(help_text='Tiempo que se planificó (hora_fin - hora_inicio)')),
                ('tiempo_real', models.DurationField(help_text='Tiempo que realmente tomó')),
                ('fecha_inicio_real', models.DateTimeField(help_text='Fecha y hora real de inicio')),
                ('fecha_fin_real', models.DateTimeField(help_text='Fecha y hora real de finalización')),
                ('defectos_detectados', models.IntegerField(default=0, help_text='Cantidad de defectos detectados')),
                ('porcentaje_calidad', models.FloatField(default=100, help_text='Porcentaje de calidad (100 = sin defectos)')),
                ('costo_materiales', models.DecimalField(blank=True, decimal_places=2, help_text='Costo real de materiales', max_digits=10, null=True)),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, help_text='Costo real de mano de obra', max_digits=10, null=True)),
                ('costo_energia', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de energía consumida', max_digits=10, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, help_text='Costo total (suma de todos los costos)', max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales sobre la producción', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se creó este registro histórico')),
                ('empleados_asignados', models.ManyToManyField(blank=True, help_text='Empleados que trabajaron en esta producción', related_name='producciones_historial', to='polls.empleado')),
                ('fabrica', models.ForeignKey(help_text='Planta donde se produjo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_producciones', to='polls.fabrica')),
                ('receta_utilizada', models.ForeignKey(blank=True, help_text='Receta base utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones_historial', to='polls.receta')),
                ('orden_produccion', models.OneToOneField(help_text='Orden de producción que generó este historial', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='polls.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Historial de Producción',
                'verbose_name_plural': 'Historiales de Producción',
                'ordering': ['-fecha_fin_real'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PRODUCCION', 'Producción'), ('ESPECIALIDAD', 'Especialidad'), ('MANTENIMIENTO', 'Mantenimiento'), ('CALIBRACION', 'Calibración')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_horas', models.IntegerField(default=0)),
                ('tiempo_minutos', models.IntegerField(default=0)),
                ('ingredientes_json', models.TextField(blank=True, help_text='JSON con lista de ingredientes', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('receta_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='polls.receta')),
            ],
            options={
                'verbose_name': 'Plantilla de Producción',
                'verbose_name_plural': 'Plantillas de Producción',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='polls.fabrica')),
            ],
            options={
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='polls.sistema'),
        ),
        migrations.CreateModel(
            name='MantenimientoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del mantenimiento', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de las tareas')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio planificada')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio planificada')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización planificada')),
                ('hora_fin', models.TimeField(help_text='Hora de finalización planificada')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Dispositivo/máquina específica (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_programados', to='polls.dispositivoscada')),
                ('fabrica', models.ForeignKey(help_text='Planta/fábrica donde se realizará', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_programados', to='polls.fabrica')),
                ('registro_mantenimiento', models.OneToOneField(blank=True, help_text='Se crea automáticamente al completar el mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimiento_programado_origen', to='polls.registromantenimiento')),
                ('sistema', models.ForeignKey(blank=True, help_text='Sistema específico (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_programados', to='polls.sistema')),
            ],
            options={
                'verbose_name': 'Mantenimiento Programado',
                'verbose_name_plural': 'Mantenimientos Programados',
                'ordering': ['fecha_inicio', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='dispositivoscada',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='polls.sistema'),
        ),
        migrations.CreateModel(
            name='UnidadAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la unidad (ej: Tanque A, Silo Norte)', max_length=100)),
                ('tipo', models.CharField(choices=[('TANK', 'Tanque'), ('SILO', 'Silo'), ('DEPOSIT', 'Depósito')], help_text='Tipo de unidad de almacenamiento', max_length=20)),
                ('contenido', models.CharField(help_text='Qué contiene actualmente (ej: Aceite de Oliva)', max_length=200)),
                ('volumen_actual', models.FloatField(default=0, help_text='Volumen actual en la unidad especificada')),
                ('capacidad', models.FloatField(help_text='Capacidad máxima en la unidad especificada')),
                ('unidad', models.CharField(default='L', help_text='Unidad de medida (L, m³, kg, etc.)', max_length=20)),
                ('temperatura', models.FloatField(blank=True, help_text='Temperatura en °C', null=True)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='ACTIVE', help_text='Estado operativo de la unidad', max_length=20)),
                ('node_id', models.CharField(blank=True, help_text='ID del nodo en diagrama SCADA (ej: tank-1)', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispositivo_sensor', models.ForeignKey(blank=True, help_text='Sensor que monitorea esta unidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_monitoreadas', to='polls.dispositivoscada')),
                ('inventario', models.ForeignKey(help_text='Inventario al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='unidades_almacenamiento', to='polls.inventario')),
            ],
            options={
                'verbose_name': 'Unidad de Almacenamiento',
                'verbose_name_plural': 'Unidades de Almacenamiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='AccidenteLaboral',
        ),
        migrations.DeleteModel(
            name='Capacitacion',
        ),
        migrations.DeleteModel(
            name='Comprador',
        ),
        migrations.DeleteModel(
            name='DetallePedidoComprador',
        ),
        migrations.DeleteModel(
            name='DetallePedidoProveedor',
        ),
        migrations.DeleteModel(
            name='DetalleResiduos',
        ),
        migrations.DeleteModel(
            name='EmpleadoCapacitacion',
        ),
        migrations.DeleteModel(
            name='EstadoItem',
        ),
        migrations.DeleteModel(
            name='EventoEspecial',
        ),
        migrations.DeleteModel(
            name='Falta',
        ),
        migrations.DeleteModel(
            name='HistorialEstadoVacacion',
        ),
        migrations.DeleteModel(
            name='Licencia',
        ),
        migrations.DeleteModel(
            name='PagoMensual',
        ),
        migrations.DeleteModel(
            name='PedidoComprador',
        ),
        migrations.DeleteModel(
            name='PedidoProveedor',
        ),
        migrations.DeleteModel(
            name='PoliticaVacaciones',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='PruebasMedicas',
        ),
        migrations.DeleteModel(
            name='RegistroFichaje',
        ),
        migrations.DeleteModel(
            name='RegistroFinanciero',
        ),
        migrations.DeleteModel(
            name='RegistroPagoTarea',
        ),
        migrations.DeleteModel(
            name='Sancion',
        ),
        migrations.DeleteModel(
            name='TipoTarifa',
        ),
        migrations.DeleteModel(
            name='Transferencia',
        ),
        migrations.DeleteModel(
            name='Vacacion',
        ),
        migrations.AddIndex(
            model_name='comunicacionmqtt',
            index=models.Index(fields=['topic', '-timestamp'], name='polls_comun_topic_0c5fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='comunicacionmqtt',
            index=models.Index(fields=['dispositivo', '-timestamp'], name='polls_comun_disposi_708dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='comunicacionmqtt',
            index=models.Index(fields=['exitoso', '-timestamp'], name='polls_comun_exitoso_eaf633_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturasensor',
            index=models.Index(fields=['dispositivo', '-timestamp'], name='polls_lectu_disposi_e4df92_idx'),
        ),
        migrations.AddIndex(
            model_name='historialproduccion',
            index=models.Index(fields=['-fecha_fin_real'], name='polls_histo_fecha_f_ef11bb_idx'),
        ),
        migrations.AddIndex(
            model_name='historialproduccion',
            index=models.Index(fields=['fabrica', '-fecha_fin_real'], name='polls_histo_fabrica_0364d4_idx'),
        ),
        migrations.AddIndex(
            model_name='historialproduccion',
            index=models.Index(fields=['producto', '-fecha_fin_real'], name='polls_histo_product_880c5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sistema',
            unique_together={('nombre', 'fabrica')},
        ),
        migrations.AddIndex(
            model_name='mantenimientoprogramado',
            index=models.Index(fields=['fecha_inicio', 'estado'], name='polls_mante_fecha_i_798dee_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientoprogramado',
            index=models.Index(fields=['fabrica', 'estado'], name='polls_mante_fabrica_0dbead_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadalmacenamiento',
            index=models.Index(fields=['node_id'], name='polls_unida_node_id_b999d0_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadalmacenamiento',
            index=models.Index(fields=['estado'], name='polls_unida_estado_a0f4a2_idx'),
        ),
    ]
