# Generated by Django 5.2.14 on 2026-06-03 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_configuracionmqtt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='configuracion',
            field=models.ForeignKey(blank=True, help_text='Configuración MQTT utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones', to='polls.configuracionmqtt'),
        ),
    ]
