# Generated by Django 5.2.13 on 2026-06-24 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_configuracionmqtt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientealmacenamiento',
            name='bombo',
        ),
        migrations.AddField(
            model_name='ingredientealmacenamiento',
            name='unidad_almacenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes_disponibles', to='polls.unidadalmacenamiento'),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='polls.configuracionmqtt'),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='direccion',
            field=models.CharField(choices=[('PUBLICADO', 'Publicado'), ('RECIBIDO', 'Recibido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones_mqtt', to='polls.dispositivoscada'),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='exitoso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='payload',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='qos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comunicacionmqtt',
            name='topic',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='cantidad_planificada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='cantidad_producida',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='costo_energia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='costo_mano_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='costo_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='defectos_detectados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='empleados_asignados',
            field=models.ManyToManyField(blank=True, related_name='producciones_historial', to='polls.empleado'),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='fabrica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_producciones', to='polls.fabrica'),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='fecha_fin_real',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='fecha_inicio_real',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='orden_produccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='polls.ordenproduccion'),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='porcentaje_calidad',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='porcentaje_cumplimiento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='producto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='receta_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones_historial', to='polls.receta'),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='tiempo_planificado',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='historialproduccion',
            name='tiempo_real',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='ingredientealmacenamiento',
            name='categoria',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Materia Prima'), ('ADDITIVE', 'Aditivo'), ('CATALYST', 'Catalizador'), ('BASE', 'Base')], default='RAW_MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_programados', to='polls.dispositivoscada'),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='fabrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_programados', to='polls.fabrica'),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='registro_mantenimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimiento_programado_origen', to='polls.registromantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimientoprogramado',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_programados', to='polls.sistema'),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='capacidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='dispositivo_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_monitoreadas', to='polls.dispositivoscada'),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='estado',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_almacenamiento', to='polls.inventario'),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='node_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='tipo',
            field=models.CharField(choices=[('TANK', 'Tanque'), ('SILO', 'Silo'), ('DEPOSIT', 'Depósito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='unidad',
            field=models.CharField(default='L', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadalmacenamiento',
            name='volumen_actual',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='BomboAlmacenamiento',
        ),
    ]
