# Generated by Django 5.2.13 on 2026-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_ingredientealmacenamiento_bombo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='unidad',
            field=models.CharField(default='UN', max_length=20),
        ),
    ]
