# Generated by Django 5.2.16 on 2026-07-20 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_ordenproduccion_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('tipo', models.CharField(choices=[('SUSCRIPCION', 'Suscripción'), ('PUBLICACION', 'Publicación')], default='SUSCRIPCION', max_length=20)),
                ('tipo_dato', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='polls.configuracionmqtt')),
            ],
            options={
                'verbose_name': 'Topic MQTT',
                'verbose_name_plural': 'Topics MQTT',
                'indexes': [models.Index(fields=['topic'], name='polls_topic_topic_0b4439_idx'), models.Index(fields=['configuracion'], name='polls_topic_configu_8c6b93_idx')],
            },
        ),
    ]
