# Generated by Django 5.2.16 on 2026-07-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave de acceso/clave de registro', max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro Config',
                'verbose_name_plural': 'Configuración de Registro',
            },
        ),
    ]
