# Generated by Django 5.2.17 on 2026-08-07 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_empleado_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(choices=[('OPERARIO', 'Operario'), ('SUPERVISOR', 'Supervisor'), ('TECNICO', 'Técnico'), ('JEFE_PLANTA', 'Jefe de Planta'), ('ADMINISTRATIVO', 'Administrativo'), ('ADMINISTRADOR', 'Administrador')], default='OPERARIO', help_text='Tipo de empleado', max_length=50),
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('modulo', models.CharField(blank=True, max_length=200, null=True)),
                ('objeto', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
