# Generated by Django 5.2.17 on 2026-08-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_empleado_tipo_empleado_registroauditoria'),
    ]

    operations = [
    ]
