# Generated by Django 5.2.17 on 2026-08-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_add_ultimo_fichaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_empleado',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESPEDIDO', 'Despedido'), ('JUBILADO', 'Jubilado'), ('SUSPENDIDO', 'Suspendido'), ('OTRO', 'Otro')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rango',
            field=models.CharField(choices=[('1', 'Director'), ('2', 'Gerente'), ('3', 'Jefe de Sección'), ('4', 'Coordinador'), ('5', 'Especialista'), ('6', 'Empleado'), ('7', 'Pasante'), ('8', 'Administrador')], max_length=50),
        ),
    ]
