# Generated by Django 5.2.17 on 2026-08-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_empleado_tipo_empleado_alter_empleado_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
