# Generated by Django 5.2.17 on 2026-08-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='rol_actual',
        ),
    ]
