# Generated by Django 5.2.17 on 2026-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_cleanup_role_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoscada',
            name='gateway_id',
            field=models.CharField(blank=True, help_text='ID del gateway/Raspberry asignado', max_length=100, null=True),
        ),
    ]
