# Generated by Django 5.2.17 on 2026-08-21 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_dispositivoscada_gateway_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('icono', models.CharField(help_text='Nombre de icono Lucide (e.g. thermometer, gauge, zap, droplet)', max_length=50)),
                ('rango_minimo', models.FloatField(default=0.0)),
                ('rango_maximo', models.FloatField(default=100.0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Métrica',
                'verbose_name_plural': 'Configuraciones de Métricas',
            },
        ),
        migrations.CreateModel(
            name='VariableVinculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_advertencia', models.FloatField(blank=True, null=True)),
                ('umbral_critico', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_vinculadas', to='polls.fabrica')),
                ('metrica_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='polls.metricaconfiguracion')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables_vinculadas', to='polls.dispositivoscada')),
            ],
            options={
                'verbose_name': 'Variable Vinculada',
                'verbose_name_plural': 'Variables Vinculadas',
                'unique_together': {('fabrica', 'metrica_config')},
            },
        ),
    ]
