# Generated by Django 5.2.17 on 2026-08-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_metricaconfiguracion_variablevinculada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_maquina', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmas_sistema', to='polls.fabrica')),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
