# Generated by Django 5.2.17 on 2026-08-21 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alarma'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarmas_sistema', to='polls.seccion'),
        ),
    ]
