# Generated by Django 5.2.17 on 2026-08-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_dispositivoscada_creado_el_seccion_creado_el'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeoAccionMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_sistema', models.CharField(choices=[('FLUIDOS', 'Fluidos / Líquidos'), ('SOLIDOS', 'Procesamiento de Sólidos'), ('EMPAQUE', 'Empaquetado y Envasado'), ('TEMPERATURA', 'Control de Temperatura'), ('GENERAL', 'Sistema General')], default='FLUIDOS', max_length=30)),
                ('nombre_accion', models.CharField(help_text='Ej: reposicion, mezcla, receta, emergencia', max_length=50)),
                ('plantilla_topico', models.CharField(default='scada/{tenant}/{gateway}/{seccion}/{sistema}/accion', max_length=255)),
                ('plantilla_payload_json', models.TextField(default='{"accion": "{accion}", "parametros": {}}')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mapeo de Acción MQTT',
                'verbose_name_plural': 'Mapeos de Acciones MQTT',
            },
        ),
    ]
