# Generated by Django 5.2.17 on 2026-09-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_mapeoaccionmqtt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='diagrama_layout_json',
            field=models.TextField(blank=True, help_text='Distribucion de nodos y conexiones de ReactFlow en JSON', null=True),
        ),
    ]
